## 应用服务 WEB 访问端口
#server:
#  port: 8888
#
#spring:
#  application:
#    name: blog-gateway
#  cloud:
#    #nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
#    nacos:
#      discovery:
#        #nacos认证信息
#        username: nacos
#        password: nacos
#        #nacos服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
#        server-addr: 127.0.0.1:8848
#        #注册到nacos的指定namespace，默认为 public
#        namespace: public
#    gateway:
#      # 路由规则
#      routes:
#        - id: blog-consumer-article # 路由的唯一标识，路由到article
#          uri: lb://blog-consumer-article  # 需要转发的地址  lb：使用nacos本地的负载均衡策略
#          # 断言规则 用于路由规则的匹配
#          predicates:
#            - Path=/article/**
#          # 过滤器
#          filters:
#            - StripPrefix=1 #转发之前去掉第一层路由
#
#        - id: blog-consumer-manage # 路由的唯一标识，路由到manage
#          uri: lb://blog-consumer-manage  # 需要转发的地址  lb：使用nacos本地的负载均衡策略
#          # 断言规则 用于路由规则的匹配
#          predicates:
#            - Path=/manage/**
#          # 过滤器
#          filters:
#            - StripPrefix=1 #转发之前去掉第一层路由